apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apns-python-wrapper
  description: Apple Push Notification Python Wrapper
  annotations:
    business-unit: EverHealth
    github.com/project-slug: drchrono/apns-python-wrapper
    product: DRC
spec:
  type: service
  lifecycle: production
  owner: EverHealth
  implementation:
    languages:
    - Python
